# Generated by Django 4.0.6 on 2022-07-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pegawaiudb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=4)),
                ('snamapegawai', models.CharField(max_length=255)),
                ('skontak', models.CharField(max_length=255)),
                ('salamat', models.CharField(max_length=255)),
                ('sposisi', models.CharField(max_length=255)),
            ],
        ),
    ]
